#! /bin/bash
payload='data=[out:xml][timeout:25];area[admin_level=4][name=Massachusetts]->.searchArea;(node["address"](area.searchArea);way["address"](area.searchArea);relation["address"](area.searchArea););(._;>;);out meta;'
echo $payload
curl -o madd.osm -g http://overpass-api.de/api/interpreter --data-urlencode "$payload"